### ISSUE TITLE
TypeError: that.write is not a function [Deno]

### ISSUE THREAD

**Issue by mvdschee** [wert-io/widget-sc-signer#4]
For our project we use [Deno](https://deno.land/) which uses ESM resolution and Typescript natively while trying to sign it will fail on the part where it's trying to create the Buffer and assign a write function to `that`. on of the limitations Deno has is it doesn't support `__proto__` see [limitations](https://deno.com/deploy/docs/runtime-api#limitations)

```bash
TypeError: that.write is not a function
    at fromString (https://cdn.skypack.dev/-/@wert-io/widget-sc-signer@v1.0.0-QlHcrmMd5hrdcppQ2Gke/dist=es2019,mode=imports/optimized/@wert-io/widget-sc-signer.js:274:21)
    at from (https://cdn.skypack.dev/-/@wert-io/widget-sc-signer@v1.0.0-QlHcrmMd5hrdcppQ2Gke/dist=es2019,mode=imports/optimized/@wert-io/widget-sc-signer.js:218:12)
    at Function.Buffer.from (https://cdn.skypack.dev/-/@wert-io/widget-sc-signer@v1.0.0-QlHcrmMd5hrdcppQ2Gke/dist=es2019,mode=imports/optimized/@wert-io/widget-sc-signer.js:223:10)
    at signSmartContractData (https://cdn.skypack.dev/-/@wert-io/widget-sc-signer@v1.0.0-QlHcrmMd5hrdcppQ2Gke/dist=es2019,mode=imports/optimized/@wert-io/widget-sc-signer.js:1623:23)
    at signer (file:///Users/maxvanderschee/Projects/clients/project-spinosaurus-serverless/signer/signer.ts:8:24)
    at handler (file:///Users/maxvanderschee/Projects/clients/project-spinosaurus-serverless/signer/main.ts:21:32)
    at Server.<anonymous> (file:///Users/maxvanderschee/Projects/clients/project-spinosaurus-serverless/signer/main.ts:70:18)
    at async Server.#respond (https://deno.land/std@0.133.0/http/server.ts:298:18)
TypeError: that.write is not a function
    at fromString (https://cdn.skypack.dev/-/@wert-io/widget-sc-signer@v1.0.0-QlHcrmMd5hrdcppQ2Gke/dist=es2019,mode=imports/optimized/@wert-io/widget-sc-signer.js:274:21)
    at from (https://cdn.skypack.dev/-/@wert-io/widget-sc-signer@v1.0.0-QlHcrmMd5hrdcppQ2Gke/dist=es2019,mode=imports/optimized/@wert-io/widget-sc-signer.js:218:12)
    at Function.Buffer.from (https://cdn.skypack.dev/-/@wert-io/widget-sc-signer@v1.0.0-QlHcrmMd5hrdcppQ2Gke/dist=es2019,mode=imports/optimized/@wert-io/widget-sc-signer.js:223:10)
    at signSmartContractData (https://cdn.skypack.dev/-/@wert-io/widget-sc-signer@v1.0.0-QlHcrmMd5hrdcppQ2Gke/dist=es2019,mode=imports/optimized/@wert-io/widget-sc-signer.js:1623:23)
    at signer (file:///Users/maxvanderschee/Projects/clients/project-spinosaurus-serverless/signer/signer.ts:8:24)
    at handler (file:///Users/maxvanderschee/Projects/clients/project-spinosaurus-serverless/signer/main.ts:21:32)
    at Server.<anonymous> (file:///Users/maxvanderschee/Projects/clients/project-spinosaurus-serverless/signer/main.ts:70:18)
    at async Server.#respond (https://deno.land/std@0.133.0/http/server.ts:298:18)
```

A small demo
```ts
import { signSmartContractData } from 'https://cdn.skypack.dev/@wert-io/widget-sc-signer';

// add your privat key here
const privatekey = '';

const options = {
    address: '0xDD8f7bD3B0b15897b40eA5B95c27ac858376243F',
    commodity: 'MATIC',
    commodity_amount: '2',
    pk_id: 'key1',
    sc_address: '0x0e452Bb8F6e67f17B2B260Cf75A43D669E4a6655',
    sc_input_data:
        '0xb723b34e0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000dd8f7bd3b0b15897b40ea5b95c27ac858376243f',
    sc_id: 'O_dvtJKmALJvDkQl-OFp8',
};

function test() {
    const signedData = signSmartContractData(options, privatekey);

    console.log(signedData);
}

test();

```

run with `deno run --allow-net --allow-hrtime --allow-env --allow-read demo.ts`

**Comment by mvdschee** [comment]
Looks like Deno doesn't support  `Buffer.from()` [buffer-from-deno](https://medium.com/deno-the-complete-reference/buffer-from-denos-equivalent-of-node-js-d42f7115af61)
